// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";

function toFn(f, param) {
  return f;
}

function useFocus(param) {
  var match = React.useState(function () {
        return false;
      });
  var setFocus = match[1];
  var onFocus = function (param) {
    return Curry._1(setFocus, (function (param) {
                  return true;
                }));
  };
  var onBlur = function (param) {
    return Curry._1(setFocus, (function (param) {
                  return false;
                }));
  };
  return [
          match[0],
          onFocus,
          onBlur
        ];
}

function useHover(param) {
  var match = React.useState(function () {
        return false;
      });
  var setIsHovered = match[1];
  var onMouseOver = function (param) {
    return Curry._1(setIsHovered, (function (param) {
                  return true;
                }));
  };
  var onMouseOut = function (param) {
    return Curry._1(setIsHovered, (function (param) {
                  return false;
                }));
  };
  return [
          match[0],
          onMouseOver,
          onMouseOut,
          setIsHovered
        ];
}

function useLog(value) {
  React.useEffect((function () {
          console.log(value);
          
        }), [value]);
  
}

var Hooks = {
  useFocus: useFocus,
  useHover: useHover,
  useLog: useLog
};

export {
  toFn ,
  Hooks ,
  
}
/* react Not a pure module */
