// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactDom from "react-dom";
import * as App$ImmutableTreeDemo from "./App.bs.js";

import './index.css'
;

var root = document.querySelector("#root");

if (!(root == null)) {
  ReactDom.render(React.createElement(App$ImmutableTreeDemo.make, {}), root);
}

export {
  
}
/*  Not a pure module */
